portal: T2D
auth:
    google:
        secretId: google-oauth-portal
        callbackHost: localhost:8090
content:
  shared: "https://raw.github.com/broadinstitute/dig-dug-shared"
  www: "file:///Users/psingh/broadProjects/dig-dug-static-resources/www"
kb:
  name: T2D
  mdv:  mdv38
  host: "ec2-34-229-106-174.compute-1.amazonaws.com"
  port: 8090
  expose:
    getRegionData:
      method: POST
      urlpath: "/dccservices/getRegionData"
    getMetadata:
      method: GET
      urlpath: "/dccservices/getMetadata"
    testme:
      method: GET
      urlpath: "/testME"
