portal: T2D
log: stdout
port: 8090
auth:
    google:
        secretId: google-oauth-portal
        callbackHost: localhost:8090
content:
    dist: ""
logins: dig-dug-logins
kb:
    name: T2D
    mdv:  mdv41
    host: "dev.type2diabeteskb.org"
    port: 80
