portal: T2D
log: portal.log
auth:
    google:
        secretId: google-oauth-portal
        callbackHost: localhost:8090
content:
    dist: "e:/workspace/dig-dug-t2dkp/dist"
kb:
    name: T2D
    mdv:  mdv41
    host: "ec2-34-229-106-174.compute-1.amazonaws.com"
    port: 8090
    expose:
        getRegionData:
            method: POST
            urlpath: "/dccservices/getRegionData"
        getMetadata:
            method: GET
            urlpath: "/dccservices/getMetadata"
        getData:
            method: POST
            urlpath: "/dccservices/getData"
        getGeneData:
            method: POST
            urlpath: "/dccservices/getGeneData"
