portal: T2D
content:
  shared: "https://raw.github.com/broadinstitute/dig-dug-shared"
  www: "file:///C:/Users/qhoang/Desktop/dig-dug-portal/dig-dug-portal/www"
kb:
  name: T2D
  mdv:  mdv38
  host: "ec2-34-229-106-174.compute-1.amazonaws.com"
  port: 8090
  expose:
    getRegionData:
      method: POST
      urlpath: "/dccservices/getRegionData"
    getMetadata:
      method: GET
      urlpath: "/dccservices/getMetadata"
    testme:
      method: GET
      urlpath: "/testME"
